---
sudo: required

language: python
python: "2.7"

env:
  - distro: centos
    version: 6
    extra_args: ''
  - distro: centos
    version: 7
    extra_args: ' --privileged  -v /sys/fs/cgroup:/sys/fs/cgroup:ro '

services:
  - docker

before_install:
  # - sudo apt-get update

install:
  # Install Ansible.
  - pip install ansible
  - /bin/bash tests/docker_prepare.sh

script:
  # first check if the code is understood by ansible
  - ansible-playbook test.yml --syntax-check

  #
  # run playbook on container
  #

  - /bin/bash tests/docker_check.sh
  - docker logs ansible_test
  # destroy container
  - docker rm -f ansible_test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
