---
sudo: required

language: python
python: "2.7"

before_install:
  # - sudo apt-get update

install:
  # Install Ansible.
  - pip install ansible

script:
  - ansible-playbook tests/test.yml --syntax-check

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
