FROM centos:6

# Install Ansible
RUN yum -y update;
RUN yum -y install sudo openssh-server;
RUN yum clean all;

# ssh port
EXPOSE 22

# Disable requiretty for sudo
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# user for ansible remote access
RUN \
    useradd -m -U -s /bin/bash provisionner && \
    mkdir -p /home/provisionner/.ssh && \
    chown -R provisionner:provisionner /home/provisionner/.ssh && \
    chmod 700 /home/provisionner/.ssh && \
    echo "provisionner ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
COPY provisionner.pub /home/provisionner/.ssh/authorized_keys
RUN chmod 500 /home/provisionner/.ssh/authorized_keys && \
    chown provisionner:provisionner /home/provisionner/.ssh/authorized_keys

ENTRYPOINT ["/sbin/init"]
