# -*- mode: ruby -*-
# vi: set ft=ruby :

# using ansible provisionning requires vagrant 1.7+
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  #config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box = "puppetlabs/centos-6.6-64-nocm"

  config.vm.host_name = "vagrant-centos6.local"

  # config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "../", "/vagrant_src", mount_options: ["dmode=555,fmode=554"]

  config.vm.provider "virtualbox" do |v|
    v.name = "vagrant_ansible_git_centos6"
    #v.gui = true
    #vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release bash-completion
  SHELL

  # 2 purposes of using ansible provisionning
  # - init box (obvious)
  # - get the invetory file generated (ex: is ssh port actually forwarded to 2222 .... or else)
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "vagrant_init.yml"
  end
end
